@WA_PeoplesManager_HostAddress = http://localhost:7033

### POST create a new person
POST {{WA_PeoplesManager_HostAddress}}/api/People
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Doe",
  "birthday": "1990-01-01T00:00:00",
  "jobs": []
}

### GET all people
GET {{WA_PeoplesManager_HostAddress}}/api/People
Accept: application/json


### PUT update a person
PUT {{WA_PeoplesManager_HostAddress}}/api/People/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Smith",
  "birthday": "1990-01-01T00:00:00",
  "jobs": []
}

### GET a person by ID
GET {{WA_PeoplesManager_HostAddress}}/api/People/1
Accept: application/json


### POST add a job to a person
POST {{WA_PeoplesManager_HostAddress}}/api/People/1/jobs
Content-Type: application/json

{
    "title": "Software Engineer",
    "companyName": "TechCorp",
    "startDate": "2020-01-01T00:00:00",
    "endDate": null
}

### POST add multiple jobs to a person
POST {{WA_PeoplesManager_HostAddress}}/api/People/1/jobs/bulk
Content-Type: application/json

[
{
    "title": "Software Engineer",
    "companyName": "TechCorp",
    "startDate": "2020-01-01T00:00:00",
    "endDate": null
    },
{
    "title": "Project Manager",
    "companyName": "BizCorp",
    "startDate": "2021-06-01T00:00:00",
    "endDate": "2023-01-01T00:00:00"
    }
]

### DELETE remove a job from a person
DELETE {{WA_PeoplesManager_HostAddress}}/api/People/1/jobs
Content-Type: application/json

{
    "title": "Software Engineer",
    "companyName": "TechCorp",
    "startDate": "2020-01-01T00:00:00",
    "endDate": null
}

### GET jobs of a person by ID
GET {{WA_PeoplesManager_HostAddress}}/api/People/1/jobs
Accept: application/json

### GET people by company name
GET {{WA_PeoplesManager_HostAddress}}/api/People/company/TechCorp
Accept: application/json

### GET jobs of a person by date range
GET {{WA_PeoplesManager_HostAddress}}/api/People/1/jobs/dates?startDate=2020-01-01T00:00:00&endDate=2023-01-01T00:00:00
Accept: application/json

### GET a person by ID
GET {{WA_PeoplesManager_HostAddress}}/api/People/1
Accept: application/json

### DELETE a person
DELETE {{WA_PeoplesManager_HostAddress}}/api/People/

### GET a person by ID
GET {{WA_PeoplesManager_HostAddress}}/api/People/1
Accept: application/json
